postgraphql:
    #image: erasche/postgraphql
    build: .
    ports:
        - "5000"
    environment:
        #DB_DEFAULT_ROLE: postgres
        DB_GRAPHQL_PATH: "/graphql"
        DB_GRAPHIQL_PATH: "/graphiql"
        PG_SECRET: "deadbeefcafe"
        DB_SCHEMA: "public"
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: postgres
        PGPORT: 5432
        PGDATABASE: postgres
    links:
        - "chado:postgres"

chado:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
        INSTALL_YEAST_DATA: 1
    volumes:
        - "./chado:/var/lib/postgresql/data"
